name: Deploy Go App to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      # --- НОВЫЙ ШАГ: Подключение к  VPN-сети Tailscale ---
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Build for Raspberry Pi
        run: GOOS=linux GOARCH=arm64 go build -o bank-api ./app

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: "bank-api"
          target: "/apps/bank-vsm-restaurant"

      - name: Restart service on Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo systemctl restart bank-api.service
            sudo systemctl status bank-api.service