name: Deploy Go App to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # ИСПРАВЛЕНО: Установлена актуальная стабильная версия Go
          go-version: '1.22'

      - name: Build for Raspberry Pi
        run: GOOS=linux GOARCH=arm64 go build -o bank-api ./app

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: "bank-api"
          # ИСПРАВЛЕНО: Указываем новый путь для копирования
          target: "/apps/bank-vsm-restaurant"

      - name: Restart service on Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo systemctl restart bank-api.service
            sudo systemctl status bank-api.service